apiVersion: batch/v1
kind: Job
metadata:
  name: job-matrix-mult-default-9
  annotations:
    scheduling/deadline-duration: "491s"  
spec:
  template:
    metadata:
      annotations:
        scheduling/deadline-duration: "491s"
      labels:
        app: matrix-mult
    spec:
      schedulerName: deadline-default-scheduler
      restartPolicy: Never
      containers:
      - name: matrix-mult
        image: evelynphs/deadline-aware-workload:matrix
        resources:
          requests:
            cpu: "1006m"
            memory: "256Mi"
        command: ["python3", "/app/matrix_mult.py", "800", "2", "78"]