apiVersion: batch/v1
kind: Job
metadata:
  name: job-matrix-mult-default-5
  annotations:
    scheduling/deadline-duration: "9s"  
spec:
  template:
    metadata:
      annotations:
        scheduling/deadline-duration: "9s"
      labels:
        app: matrix-mult
    spec:
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: matrix-mult
        image: evelynphs/deadline-aware-workload:matrix
        resources:
          requests:
            cpu: "1503m"
            memory: "128Mi"
        command: ["python3", "/app/matrix_mult.py", "200", "19", "46"]