apiVersion: batch/v1
kind: Job
metadata:
  name: job-matrix-mult-default-1
  annotations:
    scheduling/deadline-duration: "125s"  
spec:
  template:
    metadata:
      annotations:
        scheduling/deadline-duration: "125s"
      labels:
        app: matrix-mult
    spec:
      schedulerName: deadline-default-scheduler
      restartPolicy: Never
      containers:
      - name: matrix-mult
        image: evelynphs/deadline-aware-workload:matrix
        resources:
          requests:
            cpu: "1029m"
            memory: "128Mi"
        command: ["python3", "/app/matrix_mult.py", "500", "7", "9"]
