apiVersion: batch/v1
kind: Job
metadata:
  name: temp-stuffer-3
spec:
  template:
    metadata:
    spec:
      nodeName: runtime-test-cluster-worker3
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: compute-task
        image: busybox
        resources:
          requests:
            cpu: "2000m"
            memory: "1Gi"
          limits:
            cpu: "2000m"
            memory: "1Gi" 
        command: ["/bin/sh", "-c"]
        args:
        - |
          echo "Starting task 3 si pengganggu"
          echo "Processing..."
          sleep 700000
          echo "Task completed!"
---