apiVersion: batch/v1
kind: Job
metadata:
  name: job-matrix-mult-default-5
spec:
  template:
    metadata:
      labels:
        app: matrix-mult
    spec:
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: matrix-mult
        image: evelynphs/deadline-aware-workload:matrix
        command: ["/bin/sh", "-c"]
        args:
        - |
          START=$(cat /sys/fs/cgroup/cpu.stat | grep usage_usec | awk '{print $2}')
          START_TIME=$(awk '{print $1}' /proc/uptime | tr -d '.')

          python3 /app/matrix_mult.py 200 19 46

          END=$(cat /sys/fs/cgroup/cpu.stat | grep usage_usec | awk '{print $2}')
          END_TIME=$(awk '{print $1}' /proc/uptime | tr -d '.')

          CPU_US=$((END - START))
          WALL_CS=$((END_TIME - START_TIME))
          WALL_US=$((WALL_CS * 10000))
          MILLICORES=$(( (CPU_US * 1000) / WALL_US ))
          echo "END: ${END}"
          echo "END_TIME: ${END_TIME}"
          echo "START: ${START}"
          echo "START_TIME: ${START_TIME}"
          echo "WALL_CS: ${WALL_CS}"
          echo "WALL_US: ${WALL_US}"
          echo "CPU usage: ${MILLICORES}m"
