apiVersion: batch/v1
kind: Job
metadata:
  name: job-word-count-2
spec:
  template:
    metadata:
      labels:
        app: word-count
    spec:
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: word-count
        image: evelynphs/deadline-aware-scheduler:workload-test
        command: ["python3", "/app/word_count.py", "Kubernetes, also known as K8s, is an open source system for automating deployment, scaling, and management of containerized applications. It was originally designed by Google and is now maintained by the Cloud Native Computing Foundation. Kubernetes provides a platform for automating the operations of application containers across clusters of hosts, providing container-centric infrastructure. It allows you to deploy and manage applications in a cluster of machines, making it easier to scale and maintain your applications. Kubernetes has a large ecosystem of tools and services that integrate with it, making it a popular choice for container orchestration. Designed on the same principles that allow Google to run billions of containers a week, Kubernetes can scale without increasing your operations team. Whether testing locally or running a global enterprise, Kubernetes flexibility grows with you to deliver your applications consistently and easily no matter how complex your need is. Kubernetes is open source giving you the freedom to take advantage of on-premises, hybrid, or public cloud infrastructure, letting you effortlessly move workloads to where it matters to you."]
