apiVersion: batch/v1
kind: Job
metadata:
  name: job-matrix-mult-2
spec:
  template:
    metadata:
      labels:
        app: matrix-mult
    spec:
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: matrix-mult
        image: evelynphs/kube-custom-scheduler:workload-test
        command: ["python3", "/app/matrix_mult.py", "100", "3", "4"]