apiVersion: batch/v1
kind: Job
metadata:
  name: job-word-count-1
spec:
  template:
    metadata:
      labels:
        app: word-count
    spec:
      schedulerName: default-scheduler
      restartPolicy: Never
      containers:
      - name: word-count
        image: evelynphs/deadline-aware-scheduler:workload-test
        command: ["python3", "/app/word_count.py", "Hello world hello world"]
